name: .NET Core

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.102'

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
      
    - name: dotnet publish
      run: dotnet publish --configuration Release --no-build -o ${{env.DOTNET_ROOT}}/lock-patron

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'lockpatron-earthmark'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f2be84b2878d4c5ba7486e3e78cd3836 }}
        package: ${{env.DOTNET_ROOT}}/lock-patron 
